server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3313/danal
    username: danal
    password: 1234
  sql:
    init:
      platform: mysql-local
      mode: always
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: true
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

springdoc:
  version: v1
  packages-to-scan: com.lge.shield
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
    doc-expansion: none
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true